### ISSUE TITLE
RegistrationFileException stack trace printed when registration has raw time but lacks raw position

### ISSUE THREAD

**Issue by carltonwhitehead** [coner-tech/crispy-fish#42]
Review the control flow in and around the source of this error and make sure these registrations aren't omitted from query results. Also, there is no good reason an IO library should be writing directly to stdout or stderr like this.

```no-highlight
tech.coner.crispyfish.filetype.registration.RegistrationFileException: Index 0 has raw time but lacks raw position
        at tech.coner.crispyfish.filetype.registration.RegistrationMapper.toRegistration(RegistrationMapper.kt:80)
        at tech.coner.crispyfish.query.RegistrationsQuery.query(RegistrationsQuery.kt:21)
        at tech.coner.crispyfish.filetype.ecf.EventControlFile.queryRegistrations(EventControlFile.kt:59)
        at tech.coner.crispyfish.filetype.ecf.EventControlFile.queryRegistrations$default(EventControlFile.kt:54)
 ```

**Comment by carltonwhitehead** [comment]
Will be fixed in 0.5.8
